manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
    - name: j-lum
      url-base: https://github.com/j-lum
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: sora-peripheral-art
      remote: j-lum
      revision: main 
  self:
    path: config