manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
    - name: sakasosu
      url-base: https://github.com/sakasosu
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: mitsuru-superstar
      remote: sakasosu
      revision: main 
  self:
    path: config
